#!/usr/bin/env python3

import os
import sys

# realpath resolves links
thisdir = os.path.dirname(os.path.realpath(sys.argv[0]))

sys.path.append(os.path.join(thisdir, ".."))

# ruff: noqa: E402
from cooker.cooker import main

if __name__ == "__main__":
    main()
