#!/usr/bin/env python3
""" chef.py: meta build tool for Yocto Project based Linux embedded systems."""

__author__ = "Christophe BLAESS, Patrick BOETTCHER"
__license__ = "GPL"

import argparse
import jsonschema
import json
import os
import shutil
import sys

from urllib.parse import urlparse

def debug(*args):
    if ChefCall.DEBUG:
        print(*args)


def info(*args):
    print(*args)


def warn(*args):
    if ChefCall.WARNING:
        print('WARN:', *args)


def fatal_error(*args):
    print('FATAL:', *args)
    sys.exit(1)


class Config:
    DEFAULT_CONFIG_FILENAME = '.chefconfig'

    def __init__(self):
        debug('Looking for', Config.DEFAULT_CONFIG_FILENAME)

        path = os.getcwd().split(os.sep)
        while path:
            filename = '/' + os.path.join(*path, self.DEFAULT_CONFIG_FILENAME)

            debug(' Trying', filename)

            if os.path.isfile(filename):
                debug('  Found')

                self.filename = filename

                try:
                    with open(self.filename) as json_file:
                        self.cfg = json.load(json_file)
                    return
                except Exception as e:
                    fatal_error('configuration load error', e)

                break

            path.pop() # cd ..

        self.filename = os.path.join(os.getcwd(), self.DEFAULT_CONFIG_FILENAME)
        self.cfg = {}

        debug('No config-file found - using default file', self.filename)


    def project_root(self):
        return os.path.dirname(self.filename)


    def set_menu(self, menu_file):
        self.cfg['menu'] = os.path.realpath(menu_file)


    def init(self, menu_file, layer_dir, build_dir):
        self.cfg['menu'] = os.path.realpath(menu_file)

        if not os.path.isabs(layer_dir):
            layer_dir = os.path.relpath(os.path.join(self.project_root(), layer_dir), self.project_root())
        self.cfg['layer-dir'] = layer_dir

        if not os.path.isabs(build_dir):
            build_dir = os.path.relpath(os.path.join(self.project_root(), build_dir), self.project_root())
        self.cfg['build-dir'] = build_dir


    def build_dir(self, name=''):
        return os.path.join(self.project_root(), self.cfg['build-dir'], name)


    def layer_dir(self, name=''):
        return os.path.join(self.project_root(), self.cfg['layer-dir'], name)


    def menu(self):
        return self.cfg['menu']


    def save(self):
        debug('Saving configuration file')
        with open(self.filename, 'w') as json_file:
            json.dump(self.cfg, json_file, indent=4)


    def empty(self):
        return 'menu' not in self.cfg


class ChefCall:
    DEBUG = False
    WARNING = True

    DEFAULT_INIT_BUILD_SCRIPT = 'poky/oe-init-build-env'

    def __init__(self):
        parser = argparse.ArgumentParser(prog='Chef')

        parser.add_argument('--debug', action='store_true', help='activate debug printing')
        parser.add_argument('-v', '--verbose', action='store_true', help='activate verbose printing (of called subcommands)')

        # parsing subcommand's arguments
        subparsers = parser.add_subparsers(help='subcommands of Chef')

	# cook command
        cook_parser = subparsers.add_parser('cook', help='prepare the directories and build the targets of the menu')
        cook_parser.add_argument('menu', help='filename of the JSON menu', type=argparse.FileType('r'), nargs=1)
        cook_parser.add_argument('targets', help='target to build', nargs='*')
        cook_parser.set_defaults(func=self.cook)

        # init command
        init_parser = subparsers.add_parser('init', help='initialize the project-dir')
        init_parser.add_argument('-f', '--force', help='re-init an existing project',
                                 default=False, action='store_true')
        init_parser.add_argument('-l', '--layer-dir', help='path where layers will saved/cloned',
                                 default='./sources')
        init_parser.add_argument('-b', '--build-dir', help='path where the build-directories will be placed',
                                 default='.')
        init_parser.add_argument('menu', help='filename of the JSON menu', type=argparse.FileType('r'), nargs=1)
        init_parser.set_defaults(func=self.init)

        update_parser = subparsers.add_parser('update', help='update source layers')
        update_parser.set_defaults(func=self.update)

        generate_parser = subparsers.add_parser('generate', help='generate build-configuration')
        generate_parser.set_defaults(func=self.generate)

        target_info = subparsers.add_parser('target-info', help='target information')
        target_info.set_defaults(func=self.target_info)

        # prepare command (init + update + generate)
        prepare_parser = subparsers.add_parser('prepare', help='create the content of the menu')
        prepare_parser.add_argument('menu', help='filename of the JSON menu', type=argparse.FileType('r'), nargs=1)
        prepare_parser.set_defaults(func=self.prepare)

        # clear command
        #clear_parser = subparsers.add_parser('clear', help='clear the current directory')
        #clear_parser.add_argument('menu', help='filename of the JSON menu', type=argparse.FileType('r'), nargs='?')
        #clear_parser.set_defaults(func=clear_directory)

        # build command
        build_parser = subparsers.add_parser('build', help='build the targets from the menu')
        build_parser.add_argument('-s', '--sdk', action='store_true', help='build also the SDK')
        build_parser.add_argument('targets', help='target to build', nargs='*')
        build_parser.set_defaults(func=self.build_targets)

        self.clargs = parser.parse_args()

        ChefCall.DEBUG = self.clargs.debug

        # find and initialize config
        self.config = Config()

        debug('Project root', self.config.project_root())

        if self.config.empty():
            debug('empty config')
        else:
            debug('config present')

        # figure out which menu-file to use
        menu_file = None
        if 'menu' in self.clargs and self.clargs.menu is not None: # menu-file from the cmdline has priority
            menu_file = self.clargs.menu[0]
        elif not self.config.empty(): # or the one from the config-file
            try:
                menu_file = open(self.config.menu())
            except Exception as e:
                fatal_error('menu load error', e)

        self.menu = None
        if menu_file:
            try:
                self.menu = json.load(menu_file)
            except Exception as e:
                fatal_error('menu load error:', e)

            script_path = os.path.dirname(os.path.realpath(__file__))
            with open(os.path.join(script_path, 'chef-menu-schema.json')) as schema_file:
                schema = json.load(schema_file)
                try:
                    jsonschema.validate(self.menu, schema)
                except Exception as e:
                    fatal_error('menu file validation failed:', e)

                debug('menu file validation passed')

        if 'func' in self.clargs:
            self.clargs.func() # call function of selected command
        else:
            debug('no function selected, did nothing')

        sys.exit(0)


    def init(self):
        if not self.clargs.force and not self.config.empty():
            fatal_error('Project in', self.config.project_root(), 'has already been initalized')

        self.config.init(self.clargs.menu[0].name,
                         self.clargs.layer_dir,
                         self.clargs.build_dir)
        self.config.save()


    def cook(self):
        self.prepare()
        self.build_targets()


    def generate(self):
        if self.menu is None:
            fatal_error('generate needs a menu')

        info('Generating build dirs for target in project directory')

        for target, content in self.menu['targets'].items():
            directory = self.config.build_dir('build-' + target)
            self.prepare_build_directory(directory, content)


    def update(self):
        if self.menu is None:
            fatal_error('update generate needs a menu')

        info('Update layers in project directory')

        for source in self.menu['sources']:
            self.download_source(source)


    def prepare(self):
        self.config.set_menu(self.clargs.menu[0].name)
        self.config.save()

        self.update()
        self.generate()


    def download_source(self, source):
        method = 'git'
        remote_dir = ''
        local_dir = ''

        if 'method' in source:
            method = source['method']

        if method == 'ignore':
            return

        if 'dir' in source:
            local_dir = source['dir']

        if 'url' in source:
            try:
                url = urlparse(source['url'])
            except Exception as e:
                fatal_error('url-parse-error', source['url'], e)

            remote_dir = url.geturl()
            if local_dir == '':
                local_dir = url.path[1:]

        # TODO check if local dir breaks out of project-dir
        local_dir = os.path.realpath(self.config.layer_dir(local_dir))

        if not os.path.isdir(local_dir):
            self.download_directory(method, remote_dir, local_dir)

        branch = ''
        if 'branch' in source:
            branch = source['branch']

        commit = ''
        if 'commit' in source:
            commit = source['commit']

        if os.path.isdir(local_dir):
            self.update_directory(method, local_dir, remote_dir != '', branch, commit)


    def download_directory(self, method, remote_dir, local_dir):
        info('Downloading source from ', remote_dir)

        if self.clargs.verbose:
            redirect = ''
        else:
            redirect = ' >/dev/null 2>&1'

        if method == 'git':
            if os.system('git clone {} {} {}'.format(remote_dir, local_dir, redirect)) != 0:
                fatal_error('Unable to clone', remote_dir)


    def update_directory(self, method, local_dir, has_remote, branch, commit):
        if self.clargs.verbose:
            redirect = ''
        else:
            redirect = ' >/dev/null 2>&1'

        if method == 'git':

            if commit == '':

                if 'branch' == '':
                    warn('ATTENTION! source "{}" has no "commit" nor "branch" field, the build will not be reproducible at all!'.format(local_dir))
                    info('Trying to update source {}... '.format(local_dir))
                    if has_remote:
                        if os.system('cd ' + local_dir + '; git pull' + redirect) != 0:
                            fatal_error('Unable to pull updates for {}'.format(local_dir))
                else:
                    warn('source "{}" has no "commit" field, the build will not be reproducible!'.format(local_dir))
                    info('Updating source {}... '.format(local_dir))
                    if os.system('cd ' + local_dir + '; git checkout ' + branch + redirect) != 0:
                        fatal_error('Unable to checkout branch {} for {}'.format(branch, local_dir))
                    if has_remote:
                        if os.system('cd ' + local_dir + '; git pull' + redirect) != 0:
                            fatal_error('Unable to pull updates for {}'.format(local_dir))

            else:
                info('Updating source {}... '.format(local_dir))
                if os.system('cd ' + local_dir + '; git checkout ' + commit + redirect) != 0:
                    fatal_error('Unable to checkout commit {} for {}'.format(commit, local_dir))


    def prepare_build_directory(self, path, target):
        debug('Preparing directory:', path)

        os.makedirs(path, exist_ok=True)

        conf_path = os.path.join(path, 'conf')
        os.makedirs(conf_path, exist_ok=True)

        dl_dir = os.path.join(self.config.project_root(), 'downloads')
        dl_dir = '${TOPDIR}/' + os.path.relpath(dl_dir, path)

        sstate_dir = os.path.join(self.config.project_root(), 'sstate-cache')
        sstate_dir = '${TOPDIR}/' + os.path.relpath(sstate_dir, path)

        with open(os.path.join(conf_path, 'local.conf'), 'w') as file:
            file.write('\n# DO NOT EDIT! - This file is automatically created by chef.\n\n')
            for line in target['local.conf']:
                file.write(line + '\n')

            file.write('DL_DIR ?= "{}"\n'.format(dl_dir))
            file.write('SSTATE_DIR ?= "{}"\n'.format(sstate_dir))

            file.write('''DISTRO ?= "poky"
PACKAGE_CLASSES ?= "package_rpm"
BB_DISKMON_DIRS ??= "\\
\tSTOPTASKS,${TMPDIR},1G,100K \\
\tSTOPTASKS,${DL_DIR},1G,100K \\
\tSTOPTASKS,${SSTATE_DIR},1G,100K \\
\tSTOPTASKS,/tmp,100M,100K \\
\tABORT,${TMPDIR},100M,1K \\
\tABORT,${DL_DIR},100M,1K \\
\tABORT,${SSTATE_DIR},100M,1K \\
\tABORT,/tmp,10M,1K"
CONF_VERSION = "1"
''')

        with open(os.path.join(conf_path, 'bblayers.conf'), 'w') as file:
            file.write('\n# DO NOT EDIT! - This file is automatically created by chef.\n\n')
            file.write('''POKY_BBLAYERS_CONF_VERSION = "2"
BBPATH = "${TOPDIR}"
BBFILES ?= ""
''')
            file.write('BBLAYERS ?= " \\\n')
            for layer in self.menu['layers'] + target['layers']:
                layer_path = os.path.relpath(self.config.layer_dir(layer), path)
                file.write('${{TOPDIR}}/{} \\\n'.format(layer_path))
            file.write('"\n')

        with open(os.path.join(conf_path, 'templateconf.cfg'), 'w') as file:
            file.write("meta-poky/conf\n")


    def target_info(self):
        if self.menu is None:
            fatal_error('target-info needs a menu')

        for target in self.menu['targets']:
            path = self.config.build_dir('build-' + target)

            info('target', target, 'build-dir can be initialized by calling')
            info('  .',
                 os.path.relpath(self.config.layer_dir(ChefCall.DEFAULT_INIT_BUILD_SCRIPT), os.getcwd()),
                 os.path.relpath(path, os.getcwd()))


    def build_targets(self):
        debug('Building targets')

        targets = {}

        if self.clargs.targets: # filter out unwanted targets
            for target in self.clargs.targets:
                if not target in self.menu['targets']:
                    fatal_error('target', target, 'not defined in menu')
                targets[target] = self.menu['targets'][target]
        else: # use all targets
            targets = self.menu['targets']

        for name, target in targets.items():
            self.build_target(name, target)


    def build_target(self, target_name, target):
        try:
            info('Building target', target_name)

            directory = self.config.build_dir('build-' + target_name)

            if 'image' in target:
                image = target['image']
            else:
                image = 'core-image-base'

            init_script = self.config.layer_dir(ChefCall.DEFAULT_INIT_BUILD_SCRIPT)
            if not os.path.isfile(init_script):
                fatal_error('init-script', init_script, 'not found')

            command_line = 'env bash -c "source {} {} && bitbake {}"'.format(init_script, directory, image)

            debug('    Executing : "{}"'.format(command_line))
            os.system(command_line)
            if self.clargs.sdk:
                command_line = 'env bash -c "source {} {} && bitbake -c populate_sdk {}"'.format(init_script, directory, image)
                debug('    Executing : "{}"'.format(command_line))
                os.system(command_line)
        except Exception as e:
            fatal_error('build for', target_name, 'failed', e)


if __name__ == '__main__':
    ChefCall()


#def clear_directory():
#    debug('Clearing directory')
#
#    try:
#        for source in Menu['sources']:
#            remove_source(source)
#
#        for target in Menu['targets']:
#            directory = 'build-' + target
#            remove_directory(directory)
#    except:
#        raise
#    return 0
#
#
#def remove_directory(directory):
#    debug('  Removing directory "{}"'.format(directory))
#
#    if os.path.isdir(directory):
#        shutil.rmtree(directory, ignore_errors=True)
#
#
#def remove_source(source):
#    if 'url' in source:
#        try:
#            url = urlparse(source['url'])
#            remove_directory(url.path[1:])
#        except:
#            raise
#
